export const SYSTEM_LAUNCH_APP = 'SYSTEM_LAUNCH_APP';
export const USER_CONFIRM_ERROR_MODAL = 'USER_CONFIRM_ERROR_MODAL';
export const USER_CHANGE_QUERY = 'USER_CHANGE_QUERY';
export const USER_CHANGE_WATCH_STATUS = 'USER_CHANGE_WATCH_STATUS';
export const USER_CLICK_ALL_WATCH_IN_PAGE = 'USER_CLICK_ALL_WATCH_IN_PAGE';
export const USER_CLICK_ALL_UNWATCH_IN_PAGE = 'USER_CLICK_ALL_UNWATCH_IN_PAGE';
export const USER_CLICK_SUBSCRIPTIONS_PREV = 'USER_CLICK_SUBSCRIPTIONS_PREV';
export const USER_CLICK_SUBSCRIPTIONS_NEXT = 'USER_CLICK_SUBSCRIPTIONS_NEXT';
export const USER_CLICK_SEARCH_RESULTS_PREV = 'USER_CLICK_SEARCH_RESULTS_PREV';
export const USER_CLICK_SEARCH_RESULTS_NEXT = 'USER_CLICK_SEARCH_RESULTS_NEXT';
export const REDUCER_SET_SUBSCRIPTION = 'REDUCER_SET_SUBSCRIPTION';
export const REDUCER_START_SEARCHING = 'REDUCER_START_SEARCHING';
export const REDUCER_SET_SEARCH_RESULTS = 'REDUCER_SET_SEARCH_RESULTS';
export const REDUCER_SET_WATCH_STATUS = 'REDUCER_SET_WATCH_STATUS';
export const REDUCER_ADD_SUBSCRIPTION = 'REDUCER_ADD_SUBSCRIPTION';
export const REDUCER_SET_SEARCH_RESULTS_PAGENATION =
  'REDUCER_SET_SEARCH_RESULTS_PAGENATION';
export const REDUCER_START_CHANGING_ALL_WATCH_STATUS =
  'REDUCER_START_CHANGING_ALL_WATCH_STATUS';
export const REDUCER_DONE_CHANGING_ALL_WATCH_STATUS =
  'REDUCER_DONE_CHANGING_ALL_WATCH_STATUS';
export const REDUCER_CAUSE_ERROR = 'REDUCER_CAUSE_ERROR';
