export const SYSTEM_LAUNCH_APP = 'SYSTEM_LAUNCH_APP';
export const USER_CHANGE_QUERY = 'USER_CHANGE_QUERY';
export const REDUCER_SET_SUBSCRIPTION = 'REDUCER_SET_SUBSCRIPTION';
export const REDUCER_START_SEARCHING = 'REDUCER_START_SEARCHING';
export const REDUCER_SET_SEARCH_RESULTS = 'REDUCER_SET_SEARCH_RESULTS';
